version: "3.9"
services:
  frontend:
    container-name: "Holding-Frontend"
    build: app/frontend/
    port:
      - 3030:3030
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3030"]  # Caso utilize outra porta interna para o front, altere ela aqui também
      timeout: 10s
      retries: 5
    volumes:
      - ./app/frontend/:/app-frontend/
  backend:
    container-name: "Holding-Backend"
    build: app/backend/
    port:
      - 3031:3031
    environment:
      JWT_SECRET=jwt_secret
      PORT=3031
      DB_HOST=database
      DB_PORT=3306
    volumes:
      - ./app/backend/:/app-backend/
    platform: linux/x86_64
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3031"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5
    depends_on:
      - "database"
  database:
    container-name: "Holding-Database"
    image: mysql-8.0
    ports:
      - 3306:3306
    restart: "always"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=hold_DB
    cap_add:
      - SYS_NICE

    