version: "3.9"
services:
  # frontend:
  #   container_name: "HOLD-FRONTEND"
  #   build: app/frontend/
  backend:
    container_name: "HOLD-BACKEND"
    build: app/backend/
    platform: linux/x86_64
    ports:
      - 3001:3001
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=hold_database
      - DB_HOST=database
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  database:
    image: mysql:8
    platform: linux/x86_64
    ports:
      - 3036:3036
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - 81:8080
    environment:
      - SWAGGER_FILE=/tmp/openapi.yaml
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:80"]
      timeout: 10s
      retries: 5
    volumes:
      - ./app/backend:/tmp
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 80:8080
    environment:
      - SWAGGER_JSON=/tmp/openapi.json
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:80"]
      timeout: 10s
      retries: 5
    volumes:
      - ./app/backend:/tmp